# Exclude third-party themes from being scanned
sonar.exclusions=themes/**, public/**, resources/**

# Specifically tell it not to check for duplicated code in the static assets
sonar.cpd.exclusions=themes/**, static/**, public/**